-- INSERT INTO USERS(LOGIN, PASSWORD, NAME)
-- VALUES ('login1', 'password1', 'name1');

-- INSERT INTO MESSAGES(QUOTE_MESSAGE_ID, CONTENT, SENDER_ID, RECEIVER_ID, STATUS_UNREAD, STATUS_EDITED, TIME)
-- VALUES (NULL, 'somecontent', 2, 2, 1, 0, SYSDATE)

-- SELECT TO_DATE('2021/5/4 3:58:10', 'yyyy/mm/dd hh24:mi:ss'), 'sd'
-- FROM DUAL;

INSERT INTO MESSAGES(QUOTE_MESSAGE_ID,CONTENT,SENDER_ID,RECEIVER_ID,STATUS_UNREAD,STATUS_EDITED,TIME)
VALUES (null,'jjjj','2','2','1','0',TO_DATE('2021/5/4 4:33:6', 'yyyy/mm/dd hh24:mi:ss'))